# Generated by Django 5.2.6 on 2026-03-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_year', models.IntegerField(verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('description', models.TextField(verbose_name='Краткое описание')),
            ],
        ),
    ]
