# Generated by Django 5.2.6 on 2026-03-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons_photos/', verbose_name='Фотография'),
        ),
    ]
