# Generated by Django 5.2.6 on 2026-03-17 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_historicalperson_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='persons_docs/', verbose_name='Документ Word'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='persons_pdfs/', verbose_name='Документ PDF'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='persons.historicalperson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'person')},
            },
        ),
    ]
