# Generated by Django 5.2.6 on 2026-03-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperson',
            name='description_full',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
    ]
